name: 'group04'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=24.3.1
  - ipykernel=6.29.5
  - altair-all=5.4.*
  - vega_datasets=0.9.0
  - vegafusion=1.6.9
  - vegafusion-python-embed=1.6.9
  - scipy=1.14.1
  - matplotlib>=3.2.2
  - scikit-learn=1.5.2
  - requests>=2.24.0
  - graphviz=12.0.0
  - python-graphviz=0.20.3
  - eli5=0.13.0
  - shap=0.46.0
  - jinja2=3.1.4
  - lightgbm=4.5.0
  - spacy=3.8.2
  - xgboost=2.1.3
  - catboost=1.2.7
  - nltk=3.9.1
  - imbalanced-learn=0.12.4
  - conda-lock=2.5.7
  - pandera=0.21.0
  - vl-convert-python=1.6.0
  - tabulate=0.9.0
  - quarto=1.5.57
  - nbformat=5.10.4
  - nbclient=0.10.1
  - make=4.3
  - pip:
    - mglearn==0.2.0
    - spacymoji==3.1.0
    - altair_ally==0.1.1
    - pytest==7.2.0
